#!/usr/bin/env node
// Syncs upstream agent skills into .github/cloud-skills/ based on .github/skills-sources.json.
//
// .github/cloud-skills/ is a staging directory, not a discovery directory. Copilot cloud only
// reads .github/skills/, which copilot-setup-steps.yml materializes from here at session start.
// Keeping the committed copy out of .github/skills/ stops local editors - which scan that path -
// from listing these alongside the full upstream plugins.
//
// Layout produced:
//   .github/cloud-skills/_vendor/<source-id>/...  verbatim upstream subtree, plugin layout preserved
//                                                 so the skills' own ../../ relative paths still resolve
//   .github/cloud-skills/<source-id>-<skill>/     thin pointer SKILL.md that delegates to the vendored copy
//
// Usage: node .github/scripts/sync-skills.mjs

import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

const repoRoot = process.cwd();
const manifestPath = path.join(repoRoot, '.github', 'skills-sources.json');
const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));

const vendorRoot = path.join(repoRoot, ...manifest.vendorRoot.split('/'));
const skillsRoot = path.join(repoRoot, ...manifest.skillsRoot.split('/'));

function git(cwd, ...args) {
  return execFileSync('git', args, { cwd, encoding: 'utf8', stdio: ['ignore', 'pipe', 'inherit'] }).trim();
}

function rmrf(target) {
  fs.rmSync(target, { recursive: true, force: true });
}

// Pulls the YAML frontmatter block off a SKILL.md. Returns null when there is none.
function splitFrontmatter(text) {
  if (!text.startsWith('---')) return null;
  const end = text.indexOf('\n---', 3);
  if (end === -1) return null;
  const firstNewline = text.indexOf('\n');
  return {
    frontmatter: text.slice(firstNewline + 1, end + 1),
    body: text.slice(text.indexOf('\n', end + 1) + 1),
  };
}

// Extracts a single top-level key plus any folded continuation lines.
// Pointers deliberately carry only `description` - upstream keys like `agent:` and
// `allowed-tools:` reference plugin machinery that does not exist in this repo.
function extractKey(frontmatter, key) {
  const lines = frontmatter.split('\n');
  const out = [];
  let capturing = false;
  for (const line of lines) {
    if (new RegExp(`^${key}\\s*:`).test(line)) {
      capturing = true;
      out.push(line);
      continue;
    }
    if (capturing && /^(\s+\S|\s*$)/.test(line)) {
      out.push(line);
      continue;
    }
    if (capturing) break;
  }
  return out.join('\n').trimEnd();
}

function checkoutSource(source) {
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), `skills-${source.id}-`));
  const prefix = source.pluginPath ? `${source.pluginPath}/` : '';
  const enabled = source.skills.filter((s) => s.enabled);
  const sparsePaths = [
    ...source.supportPaths.map((p) => `${prefix}${p}`),
    ...enabled.map((s) => `${prefix}${source.skillsPath}/${s.name}`),
  ];

  git(tmp, 'init', '--quiet');
  git(tmp, 'remote', 'add', 'origin', `https://github.com/${source.repo}.git`);
  git(tmp, 'sparse-checkout', 'init', '--cone');
  git(tmp, 'sparse-checkout', 'set', ...sparsePaths);
  git(tmp, 'fetch', '--quiet', '--depth=1', 'origin', source.ref);
  git(tmp, 'checkout', '--quiet', 'FETCH_HEAD');

  return { tmp, sha: git(tmp, 'rev-parse', 'FETCH_HEAD'), prefix, enabled };
}

function writePointer(source, skill, upstreamSkillDir, vendorRelDir) {
  const upstreamSkillMd = path.join(upstreamSkillDir, 'SKILL.md');
  if (!fs.existsSync(upstreamSkillMd)) {
    throw new Error(`${source.repo}: ${skill.name} has no SKILL.md at the expected path`);
  }

  const raw = fs.readFileSync(upstreamSkillMd, 'utf8');
  const split = splitFrontmatter(raw);
  const pointerName = `${source.id}-${skill.name}`;
  const description = split ? extractKey(split.frontmatter, 'description') : '';
  const frontmatter = description
    ? `name: ${pointerName}\n${description}`
    : `name: ${pointerName}\ndescription: Vendored ${skill.name} skill from ${source.repo}.`;

  const pointerDir = path.join(skillsRoot, pointerName);
  fs.mkdirSync(pointerDir, { recursive: true });
  fs.writeFileSync(
    path.join(pointerDir, 'SKILL.md'),
    [
      '---',
      frontmatter,
      '---',
      '',
      `# ${pointerName}`,
      '',
      '> Generated by `.github/scripts/sync-skills.mjs`. Do not edit by hand.',
      '',
      `The full instructions for this skill live in the vendored upstream copy at`,
      `\`${vendorRelDir}/SKILL.md\`. Read that file and follow it.`,
      '',
      `Any relative paths it references (\`../../scripts\`, \`../../templates\`, and so on) resolve`,
      `inside \`${manifest.vendorRoot}/${source.id}/\`, which mirrors the upstream plugin layout.`,
      '',
      `Source: https://github.com/${source.repo} (${source.license})`,
      '',
    ].join('\n'),
  );
}

function prunePointers(sourceId, keep) {
  if (!fs.existsSync(skillsRoot)) return;
  for (const entry of fs.readdirSync(skillsRoot, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    if (!entry.name.startsWith(`${sourceId}-`)) continue;
    if (keep.has(entry.name)) continue;
    rmrf(path.join(skillsRoot, entry.name));
  }
}

const notice = [
  '# Vendored agent skills',
  '',
  'Everything under this directory is copied verbatim from upstream repositories by',
  '`.github/scripts/sync-skills.mjs`. Do not edit these files - changes are overwritten on the next sync.',
  '',
  'To change what is vendored, edit `.github/skills-sources.json` and re-run the Sync Skills workflow.',
  '',
  '| Source | Upstream repository | Ref | Commit | License |',
  '| --- | --- | --- | --- | --- |',
];

let syncedAny = false;

for (const source of manifest.sources) {
  const enabledCount = source.skills.filter((s) => s.enabled).length;
  const sourceVendorDir = path.join(vendorRoot, source.id);

  if (enabledCount === 0) {
    rmrf(sourceVendorDir);
    prunePointers(source.id, new Set());
    continue;
  }

  console.log(`Syncing ${source.id} (${enabledCount} skills) from ${source.repo}@${source.ref}`);
  const { tmp, sha, prefix, enabled } = checkoutSource(source);

  try {
    rmrf(sourceVendorDir);
    fs.mkdirSync(sourceVendorDir, { recursive: true });

    for (const support of source.supportPaths) {
      const src = path.join(tmp, ...`${prefix}${support}`.split('/'));
      if (!fs.existsSync(src)) continue;
      fs.cpSync(src, path.join(sourceVendorDir, ...support.split('/')), { recursive: true });
    }

    const keep = new Set();
    for (const skill of enabled) {
      const rel = `${source.skillsPath}/${skill.name}`;
      const src = path.join(tmp, ...`${prefix}${rel}`.split('/'));
      if (!fs.existsSync(src)) {
        throw new Error(`${source.repo}: ${rel} no longer exists upstream - update the manifest`);
      }
      fs.cpSync(src, path.join(sourceVendorDir, ...rel.split('/')), { recursive: true });
      writePointer(source, skill, src, `${manifest.vendorRoot}/${source.id}/${rel}`);
      keep.add(`${source.id}-${skill.name}`);
    }

    for (const excluded of source.excludePaths ?? []) {
      rmrf(path.join(sourceVendorDir, ...excluded.split('/')));
    }

    prunePointers(source.id, keep);

    // Only stamp the time when the upstream commit actually moved. Stamping every run would
    // make the manifest differ on every sync, so the drift check could never report "no change".
    if (source.lastSyncedSha !== sha) {
      source.lastSyncedSha = sha;
      source.lastSyncedAt = new Date().toISOString().replace(/\.\d{3}Z$/, 'Z');
    }
    syncedAny = true;
    notice.push(`| \`${source.id}\` | ${source.repo} | ${source.ref} | \`${sha}\` | ${source.license} |`);
  } finally {
    rmrf(tmp);
  }
}

if (syncedAny) {
  fs.mkdirSync(vendorRoot, { recursive: true });
  fs.writeFileSync(path.join(vendorRoot, 'NOTICE.md'), `${notice.join('\n')}\n`);
} else {
  rmrf(vendorRoot);
}

fs.writeFileSync(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);
console.log('Done.');
